#!/bin/bash

mysql --protocol=socket -uroot -p$DATABASE_PASSWORD <<EOSQL
CREATE USER '$DATABASE_USER'@'%' IDENTIFIED BY '$DATABASE_PASSWORD';
GRANT ALL PRIVILEGES ON *.* TO '$DATABASE_USER'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
EOSQL


